import type { FastifyInstance } from 'fastify';
import { registerAuthRoutes } from './auth';
import { registerSecurityRoutes } from './security';
import { registerMetaRoutes } from './meta';
import { registerProfileRoutes } from './profile';
import { registerCategoryRoutes } from './categories';
import { registerAccountRoutes } from './accounts';
import { registerTransactionRoutes } from './transactions';
import { registerBudgetRoutes } from './budgets';
import { registerGoalRoutes } from './goals';
import { registerSubscriptionRoutes } from './subscriptions';
import { registerDebtRoutes } from './debts';
import { registerRecurringRoutes } from './recurring';
import { registerNotificationRoutes } from './notifications';
import { registerDashboardRoutes } from './dashboard';
import { registerAnalyticsRoutes } from './analytics';
import { registerIntelligenceRoutes } from './intelligence';
import { registerReportRoutes } from './reports';
import { registerJournalRoutes } from './journal';
import { registerSearchRoutes } from './search';
import { registerImportExportRoutes } from './importExport';
import { registerReceiptRoutes } from './receipts';
import { registerAdminRoutes } from './admin';
import { registerPrivacyRoutes } from './privacy';
import { registerDevRoutes } from './dev';

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await registerMetaRoutes(app);
  await registerAuthRoutes(app);
  await registerSecurityRoutes(app);
  await registerProfileRoutes(app);
  await registerCategoryRoutes(app);
  await registerAccountRoutes(app);
  await registerTransactionRoutes(app);
  await registerBudgetRoutes(app);
  await registerGoalRoutes(app);
  await registerSubscriptionRoutes(app);
  await registerDebtRoutes(app);
  await registerRecurringRoutes(app);
  await registerNotificationRoutes(app);
  await registerDashboardRoutes(app);
  await registerAnalyticsRoutes(app);
  await registerIntelligenceRoutes(app);
  await registerReportRoutes(app);
  await registerJournalRoutes(app);
  await registerSearchRoutes(app);
  await registerImportExportRoutes(app);
  await registerReceiptRoutes(app);
  await registerAdminRoutes(app);
  await registerPrivacyRoutes(app);
  await registerDevRoutes(app);
}
